src/Entity/Matiere.php
<?php

namespace App\Entity;

use App\Repository\MatiereRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MatiereRepository::class)
 */
class Matiere
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\ManyToOne(targetEntity=Intervenant::class, inversedBy="setMatiere")
     */
    private $fk_intervenant;

    /**
     * @ORM\ManyToMany(targetEntity=Calendrier::class, mappedBy="fk_matiere")
     */
    private $setMatiere;

    public function __construct()
    {
        $this->setMatiere = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->intitule;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getFkIntervenant(): ?Intervenant
    {
        return $this->fk_intervenant;
    }

    public function setFkIntervenant(?Intervenant $fk_intervenant): self
    {
        $this->fk_intervenant = $fk_intervenant;

        return $this;
    }

    /**
     * @return Collection|Calendrier[]
     */
    public function getSetMatiere(): Collection
    {
        return $this->setMatiere;
    }

    public function addSetMatiere(Calendrier $setMatiere): self
    {
        if (!$this->setMatiere->contains($setMatiere)) {
            $this->setMatiere[] = $setMatiere;
            $setMatiere->addFkMatiere($this);
        }

        return $this;
    }

    public function removeSetMatiere(Calendrier $setMatiere): self
    {
        if ($this->setMatiere->removeElement($setMatiere)) {
            $setMatiere->removeFkMatiere($this);
        }

        return $this;
    }
}

src/Controller/Secretaire.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class Secretaire
{
    /**
     * @Route("/connexion_secretaire")
     */

    function ConnexionSecretaire()
    {
        return new Response("Future page de connexion de la secretaire");
    }
}

src/Controller/SecretaireController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Calendrier;
use App\Entity\Matiere;
use App\Form\CalendrierFormType;
use App\Form\MatiereFormType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class SecretaireController extends AbstractController
{
    /**
     * @Route("/connexion_secretaire")
     */

    function ConnexionSecretaire()
    {
        return new Response("Future page de connexion de la secretaire");
    }

    /**
     * @Route("/matieres")
     */

    function listMatieres(){
        $matieres = $this->getDoctrine()->getRepository(Matiere::class)->findAll();
        return $this->render('secretaire/list_matieres.html.twig', ['Matieres'=>$matieres,]);
    }

    /**
     * @Route("/matieres/ajouter")
     */

    function ajouterMatieres(Request $request){

        #Create a new date for calendar
        $task = new Matiere();

        $matiere = $this->createForm(MatiereFormType::class, $task);

        $matiere->handleRequest($request);

        if($matiere->isSubmitted() && $matiere->isValid()){
            $task = $matiere->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('newMatiere_success');
        }

        return $this->render('secretaire/matiere_add.html.twig', ['MatiereForm'=>$matiere->createView(), ]);

    }


    /**
     * @Route ("/matieres/supprimer")
     */

    function deleteMatieres(){
        $repository = $this->getDoctrine()->getRepository(Matiere::class);
        $matiere = $repository->findAll();
        $entityManager = $this->getDoctrine()->getManager();
        foreach ($matiere as $matieres) {
            $entityManager->remove($matieres);
        }
        $entityManager->flush();
        return $this->render('secretaire/matiere_delete.html.twig');
    }



    /**
     * @Route ("/calendrier")
     */

    function voirCalendrier(){
        $date = $this->getDoctrine()->getRepository(Calendrier::class)->findAll();

        return $this->render('calendrier/calendrier.html.twig', ['Calendriers'=>$date,]);
    }

    /**
     * @Route ("/calendrier/{id}/edit", name="calendar_event_edit", methods={"PUT"})
     */

    function editCalendrier(ManagerRegistry $doctrine, ?Calendrier $calendrier, Request $request){
        $data = json_decode($request->getContent());

        if
        (
            isset($data->title) && !empty($data->title) &&
            isset($data->start) && !empty($data->start) &&
            isset($data->end) && !empty($data->end)
        ){
            //Complet
            $status_code = 200;

            if(!$calendrier){
                $calendrier = new Calendrier();

                $status_code = 201;
            }

            $calendrier->setNomCours($data->title);
            $calendrier->setDateStart(new DateTime($data->start));
            $calendrier->setDateEnd(new DateTime($data->end));

            $em = $doctrine->getManager();
            $em->persist($calendrier);
            $em->flush();

            return new Response("OK", $status_code);

        }else{
            return new Response("NOT FOUND", 404);
        }


    }

    /**
     * @Route ("/calendrier/ajouter")
     */

    function AjouterDate(Request $request){
        #Create a new date for calendar
        $task = new Calendrier();

        $calendar = $this->createForm(CalendrierFormType::class, $task);

        $calendar->handleRequest($request);

        if($calendar->isSubmitted() && $calendar->isValid()){
            $task = $calendar->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('newDateCalendar_success');
        }

        return $this->render('secretaire/calendrier_add_date.html.twig', ['CalendrierForm'=>$calendar->createView(), ]);
    }

    /**
     * @Route ("/calendrier/supprimer")
     */

    function deleteCalendrier(){
        $repository = $this->getDoctrine()->getRepository(Calendrier::class);
        $date = $repository->findAll();
        $entityManager = $this->getDoctrine()->getManager();
        foreach ($date as $dates) {
            $entityManager->remove($dates);
        }
        $entityManager->flush();
        return $this->render('secretaire/calendrier_delete_date.html.twig');
    }

}

templates/secretaire/calendrier_add_date.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pronote v9000{% endblock %}</title>
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
</head>
<body>
    {% block body %}
        {{form(CalendrierForm)}}
    {% endblock %}
    <br>
    <a href="{{ path('app_accueil_accueil') }}">Retour à l'accueil</a>
</body>
</html>

templates/secretaire/calendrier_delete_date.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pronote v9000{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
</head>
<body>
    <p>Cours supprimés</p>
    <a href="{{ path('app_accueil_accueil') }}">Retour à l'accueil</a>
</body>
</html>

templates/secretaire/list_matieres.html.twig
<head>
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
</head>

{% for Matiere in Matieres %}
    <tr>
        <td>Nom de la matière : {{ Matiere.intitule }}</td><br>
        <td>Durée (en minutes) : {{ Matiere.duree }}</td><br>
        <td>Intervenant : {{ Matiere.fkIntervenant.nom }}</td><br><br>
    </tr><br>
{% endfor %}
<a href="{{ path('app_accueil_accueil') }}">Retour à l'accueil</a>

templates/secretaire/matiere_add.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pronote v9000{% endblock %}</title>
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
</head>
<body>
{% block body %}
    {{form(MatiereForm)}}
{% endblock %}
<br>
<a href="{{ path('app_accueil_accueil') }}">Retour à l'accueil</a>
</body>
</html>

templates/secretaire/matiere_delete.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pronote v9000{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
</head>
<body>
    <p>Matières supprimés</p>
    <a href="{{ path('app_accueil_accueil') }}">Retour à l'accueil</a>
</body>
</html>