src/Entity/Calendrier.php
<?php

namespace App\Entity;

use App\Repository\CalendrierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CalendrierRepository::class)
 */
class Calendrier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomCours;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateStart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateEnd;

    /**
     * @ORM\ManyToMany(targetEntity=Intervenant::class, inversedBy="setCalendars")
     */
    private $fk_intervenant;

    /**
     * @ORM\ManyToMany(targetEntity=Matiere::class, inversedBy="setMatiere")
     */
    private $fk_matiere;


    public function __construct()
    {
        $this->fk_intervenant = new ArrayCollection();
        $this->fk_matiere = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->NomCours;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCours(): ?string
    {
        return $this->NomCours;
    }

    public function setNomCours(string $NomCours): self
    {
        $this->NomCours = $NomCours;

        return $this;
    }

    /**
     * @return Collection|Intervenant[]
     */
    public function getFkIntervenant(): Collection
    {
        return $this->fk_intervenant;
    }

    public function addFkIntervenant(Intervenant $fkIntervenant): self
    {
        if (!$this->fk_intervenant->contains($fkIntervenant)) {
            $this->fk_intervenant[] = $fkIntervenant;
        }

        return $this;
    }

    public function removeFkIntervenant(Intervenant $fkIntervenant): self
    {
        $this->fk_intervenant->removeElement($fkIntervenant);

        return $this;
    }

    /**
     * @return Collection|Matiere[]
     */
    public function getFkMatiere(): Collection
    {
        return $this->fk_matiere;
    }

    public function addFkMatiere(Matiere $fkMatiere): self
    {
        if (!$this->fk_matiere->contains($fkMatiere)) {
            $this->fk_matiere[] = $fkMatiere;
        }

        return $this;
    }

    public function removeFkMatiere(Matiere $fkMatiere): self
    {
        $this->fk_matiere->removeElement($fkMatiere);

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->DateStart;
    }

    public function setDateStart(\DateTimeInterface $DateStart): self
    {
        $this->DateStart = $DateStart;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->DateEnd;
    }

    public function setDateEnd(\DateTimeInterface $DateEnd): self
    {
        $this->DateEnd = $DateEnd;

        return $this;
    }
}

templates/calendrier/calendrier.html.twig
<!DOCTYPE html>
<html>
    <head>
        <title>Calendrier</title>
        <meta charset="UTF-8">

        <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
        <link href="{{ asset('css/fullcalendar.min.css') }}" rel="stylesheet">
        <script src="{{ asset('js/fullcalendar.min.js') }}"></script>

        {% block stylesheets %}
        <style>
            #calendrier{
                width: 80%;
                margin: auto;
            }
        </style>
        {% endblock %}

    </head>

    <body>
        <a href="{{ path('app_accueil_accueil') }}">Retour à l'accueil</a>
        {% block body %}
        <div id="calendrier">
            events: [
            {% for Calendrier in Calendriers %}
                Titre : "{{ Calendrier.nomCours }}"
                DateStart : {{ Calendrier.dateStart|date('Y-m-d H:i:s') }}
                DateEnd : {{ Calendrier.dateEnd|date('Y-m-d H:i:s') }}
            {% endfor %}
            ]
        </div>
        {% endblock %}

        {% block javascripts %}
        <script>
            window.onload = () => {
                let calendarElt = document.querySelector("#calendrier")

                let calendar = new FullCalendar.Calendar(calendarElt, {
                    initialView: "timeGridWeek",
                    locale: 'fr',
                    timeZone: 'Europe/Paris',
                    headerToolbar: {
                        start: 'prev,next today',
                        center: 'title',
                        end: 'dayGridMonth,timeGridWeek'
                    },
                    editable: true,
                    events: [
                        {% for Calendrier in Calendriers %}
                        {
                            id: '{{ Calendrier.id }}',
                            title: '{{ Calendrier.nomCours }}',
                            start: '{{ Calendrier.dateStart|date("Y-m-d H:i:s") }}',
                            end: '{{ Calendrier.dateEnd|date('Y-m-d H:i:s') }}',
                        },
                        {% endfor %}
                    ]
                })

                calendar.on('eventChange', (e) => {
                    console.log(e)
                    let url = `/calendrier/${e.event.id}/edit`

                    let data = {
                        "title": e.event.title,
                        "start": e.event.start,
                        "end": e.event.end
                    }

                    let xhr = new XMLHttpRequest

                    xhr.open("PUT", url);
                    xhr.send(JSON.stringify(data))
                })

                calendar.render()
            }
        </script>
        {% endblock %}

    </body>
</html>